### ISSUE TITLE
Time-out on Google Doc for SHARE Project

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2340]
Specific to this project at the moment: https://osf.io/68ymx/

# Steps
Under Google Drive, in the meeting notes folder, click to open this file "2015-03-09 Joint WG Meeting Notes.gdoc"

# Expected
File will render and be readable

# Actual
Error occurs: "Timeout occurred while loading, please refresh the page"

The original file set to “anyone with the link can view" is here:
https://docs.google.com/document/d/1oWFr_OyoCjERqFSLdl_9Fp_TM8lYpLBb28CMK3ODUa0/edit?usp=sharing

**Comment by lbanner** [comment]
@sloria or @kushG ? Thanks -

**Comment by sloria** [comment]
Looking into it now.

@lbanner Are you able to render other gdoc files?

**Comment by kushG** [comment]
@lbanner seems to be working correctly on my system.
![screen shot 2015-03-27 at 11 08 58 am](https://cloud.githubusercontent.com/assets/8779995/6870317/b711c6da-d471-11e4-9480-216e20fc6793.png)

**Comment by lbanner** [comment]
Interesting ... @erinspace did replicate the SHARE issue, and I am having the same 'time-out' error with this project just setup: https://osf.io/n68yt/files/

@nicipfeiffer -- when you get a chance can you check + replicate?

**Comment by GaryKriebel** [comment]
I am experiencing the same thing that @lbanner is.  I tried another Google Doc and also received a time out. 

Google Sheet is rendering fine, as @kushG pointed out.

**Comment by nicipfeiffer** [comment]
@lbanner and @sloria I replicated the issue.  Even creating a new gdoc, giving permission, then upload to a project on osf persists with render time out.

**Comment by sloria** [comment]
Replicated this locally and got a traceback:

```
Traceback (most recent call last):
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sloria/projects/cos-projects/osf/framework/routing/__init__.py", line 96, in wrapped
    data = fn(*args, **kwargs)
  File "/Users/sloria/projects/cos-projects/osf/website/views.py", line 397, in resolve_guid
    return proxy_url(url)
  File "/Users/sloria/projects/cos-projects/osf/framework/routing/__init__.py", line 231, in proxy_url
    response = app.view_functions[match[0]](**match[1])
  File "/Users/sloria/projects/cos-projects/osf/framework/routing/__init__.py", line 96, in wrapped
    data = fn(*args, **kwargs)
  File "/Users/sloria/projects/cos-projects/osf/website/project/decorators.py", line 52, in wrapped
    return func(*args, **kwargs)
  File "/Users/sloria/projects/cos-projects/osf/website/project/decorators.py", line 132, in wrapped
    return response or func(*args, **kwargs)
  File "/Users/sloria/projects/cos-projects/osf/website/addons/base/views.py", line 308, in addon_view_or_download_file
    return addon_view_file(auth, node, node_addon, file_guid, extras)
  File "/Users/sloria/projects/cos-projects/osf/website/addons/base/views.py", line 326, in addon_view_file
    'rendered': get_or_start_render(file_guid),
  File "/Users/sloria/projects/cos-projects/osf/website/addons/base/views.py", line 233, in get_or_start_render
    file_guid.public_download_url
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/sloria/projects/cos-projects/osf/framework/render/tasks.py", line 75, in _build_rendered_html
    render_result = mfr.render(temp_file, src=public_download_url)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/core.py", line 124, in render
    return handler.render(fp, renderer=renderer, *args, **kwargs)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/core.py", line 231, in render
    return render_func(fp, *args, **kwargs)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/ext/docx/render.py", line 16, in render_docx
    content = Docx2Html(fp).parsed_without_head
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/pydocx/parsers/Docx2Html.py", line 36, in parsed_without_head
    content = super(Docx2Html, self).parsed
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/pydocx/DocxParser.py", line 778, in parsed
    self._load()
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/pydocx/DocxParser.py", line 219, in _load
    self.page_width = self._get_page_width(main_document_part.root_element)
  File "/Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/pydocx/DocxParser.py", line 249, in _get_page_width
    pgSz = int(pgSzEl.attrib['w'])
```

This seems to have been fixed recently by https://github.com/CenterForOpenScience/pydocx/pull/113 . 

We are currently pinning MFR's DocX renderer to @mfraezz 's fork of pydocx (which does not have that fix).

@mfraezz Are there any barriers to using the latest version of pydocx (esp. since https://github.com/CenterForOpenScience/pydocx/pull/95 has been addressed)?

**Comment by sloria** [comment]
Ok, looks like the only barrier is removing the inline styling (see https://github.com/CenterForOpenScience/pydocx/issues/102), but we can get away with the workaround described in that issue.

I've updated mfr to use the latest version of pydocx. Will send a hotfix with the version update shortly.

**Comment by lbanner** [comment]
Nice work!

**Comment by sloria** [comment]
Should be fixed now.

**Comment by lbanner** [comment]
Looks good! TY
