### ISSUE TITLE
[bug][staging2] Swagger + other errors when running DRF+FlaskRequestMiddleware

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#3376]
## Summary
Changes made in #3303 (adding a FlaskRequestMiddleware) are apparently breaking the Swagger documentation. (and other things)

## Steps to reproduce
1. Run the API server with the newest develop branch
2. Go to the API documentation page:
3. There should be an error at the top of the page:
`Unable to read api 'v2' from path http://localhost:8000/v2/docs/api-docs/v2 (server returned INTERNAL SERVER ERROR)`
4. In `osf.io/api/base/settings/defaults.py`, comment out the following line:
`'api.base.middleware.FlaskRequestMiddleware',`
5. Reload. The error should disappear and swagger docs should appear normally

## Debugging information/ Preliminary diagnosis
Using the "network" tab in chrome to view the stacktrace gives the following error (screenshot of the "response" tab in dev tools pane)
![screen shot 2015-06-29 at 10 35 58 am](https://cloud.githubusercontent.com/assets/2957073/8410205/b226f910-1e4a-11e5-8703-b1d7e590a950.png)

It appears that something about the number and timing of Swagger requests is causing the middleware to pop the wrong request context. This results in a 500 error that prevents Swagger from loading correctly.

**Comment by abought** [comment]
I've followed up a bit, and there are two problems. A sample modification for `api.base.midddleware.FlaskRequestMiddleware` is presented that fixes the issues in a single local test case, but I'm not thrilled with this solution and still unclear on some of the internals that make it necessary. Suggestions, @lyndsysimon ?

## Issue one: Popping the wrong request context
The `FlaskRequestMiddleware` object appears to be re-used by a single instance of WSGIHandler. This means that multiple requests are trying to share the same value of `self.flask_request_ctx`, which is bound to end badly. 

Storing is in a local dictionary keyed on request would ensure we are popping the correct request context for this request.

## Issue two: Popping a request context calls sys.exc_clear()
Popping a request context calls `flask.ctx`, line 348, which calls `sys.exc_clear` when `_implicit_app_ctx_stack` is empty.

When raising an exception after this point, `django.core.handlers.base` (line 223) uses `sys.exc_info()`... which the flask context teardown code has helpfully emptied out.

One proposed solution is to re-raise the exception. But doing it inside `process_exception` is not best practice. A better way would be to jigger the flask context stacks to make sure that flask never chooses to call sys.exc_clear().

## Sample code
```python
class FlaskRequestMiddleware(object):
    """
    Push and pop new flask request contexts alongside Django requests

    This is required to prevent caching issues with ModularODM, since (Flask)StoredObject is keyed on the flask
    request object.
    """
    contexts = {}  # Middleware objects are reused across requests; make sure we're getting the right context

    def process_request(self, request):
        ## Called on every request, so self.flask_ctx should always be defined
        dummy_app_context.push()
        flask_ctx = dummy_app.test_request_context()
        self.contexts[request] = flask_ctx
        flask_ctx.push()

    def process_exception(self, request, exception):
        if _app_ctx_stack.top and request in self.contexts:
            flask_ctx = self.contexts.pop(request)
            flask_ctx.pop()

        # print "----Found an exception that triggered this function!!- called inside"  #
        # import traceback
        # print exception
        raise exception
        return None

    def process_response(self, request, response):
        if _app_ctx_stack.top and request in self.contexts:
            flask_ctx = self.contexts.pop(request)
            flask_ctx.pop()
        return response
```

**Comment by abought** [comment]
The changes discussed above fix two problems that prevent the Swagger docs from working intelligibly, but they do **not** fix a third problem as reported by @pattisdr :

On the branch https://github.com/CenterForOpenScience/osf.io/pull/3316 , sending a POST request to route `http://localhost:8000/v2/nodes/<node_id>/registrations/` fails with a celery-related error (see below).  If `FlaskRequestMiddleware` is disabled (by commenting out that line in in `api.base.settings.defaults`), the view works as expected and intended. I will work on tracking this issue next.

Traceback below.

```
Traceback (most recent call last):
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create
    self.perform_create(serializer)
  File "/Users/andyboughton/code/cos/osf.io/api/nodes/views.py", line 175, in perform_create
    serializer.save(creator=user)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 165, in save
    self.instance = self.create(validated_data)
  File "/Users/andyboughton/code/cos/osf.io/api/nodes/serializers.py", line 156, in create
    data=None
  File "/Users/andyboughton/code/cos/osf.io/website/project/model.py", line 1783, in register_node
    project_signals.after_create_registration.send(self, dst=registered, user=auth.user)
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/Users/andyboughton/code/cos/osf.io/website/archiver/listeners.py", line 38, in after_register
    celery.chain(*archive_tasks)
  File "/Users/andyboughton/code/cos/osf.io/framework/tasks/handlers.py", line 41, in enqueue_task
    if signature not in g._celery_tasks:
  File "/Users/andyboughton/code/cos/osf.io/env/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute '_celery_tasks'
```

**Comment by abought** [comment]
#3389 was merged. I'll close this one barring further reports.
