### ISSUE TITLE
"Invoke server" fails with: AttributeError: 'module' object has no attribute 'dropbox_account_list'

### ISSUE THREAD

**Issue by TomBaxter** [CenterForOpenScience/osf.io#4758]
Perhaps I'm missing a config file for dropbox? Possibly related to PR #4658

(osf)tkb:osf.io$ invoke server
[website.util.paths]  WARNING: Skipping load of "webpack-assets.json" in DEBUG_MODE.
[website.project.metadata.authorizers]  INFO: No local.json found to populate lists of DraftRegistrationApproval authorizers.
Traceback (most recent call last):
  File "/home/tkb/.virtualenvs/cos/osf/bin/invoke", line 11, in <module>
    sys.exit(main())
  File "/home/tkb/.virtualenvs/cos/osf/local/lib/python2.7/site-packages/invoke/cli.py", line 304, in main
    dispatch(sys.argv)
  File "/home/tkb/.virtualenvs/cos/osf/local/lib/python2.7/site-packages/invoke/cli.py", line 297, in dispatch
    return executor.execute(*tasks, dedupe=dedupe)
  File "/home/tkb/.virtualenvs/cos/osf/local/lib/python2.7/site-packages/invoke/executor.py", line 90, in execute
    task=task, name=name, args=args, kwargs=kwargs
  File "/home/tkb/.virtualenvs/cos/osf/local/lib/python2.7/site-packages/invoke/executor.py", line 131, in _execute
    result = task(*args, **kwargs)
  File "/home/tkb/.virtualenvs/cos/osf/local/lib/python2.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/home/tkb/work/venv/cos/osf/osf.io/tasks.py", line 47, in server
    app = init_app(set_backends=True, routes=True)
  File "/home/tkb/work/venv/cos/osf/osf.io/website/app.py", line 119, in init_app
    init_addons(settings, routes)
  File "/home/tkb/work/venv/cos/osf/osf.io/website/app.py", line 44, in init_addons
    addon = init_addon(app, addon_name, routes=routes)
  File "/home/tkb/work/venv/cos/osf/osf.io/website/addons/base/__init__.py", line 1013, in init_addon
    addon_module = importlib.import_module(import_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tkb/work/venv/cos/osf/osf.io/website/addons/dropbox/__init__.py", line 3, in <module>
    from website.addons.dropbox import model, routes, views
  File "/home/tkb/work/venv/cos/osf/osf.io/website/addons/dropbox/routes.py", line 14, in <module>
    views.dropbox_account_list,
AttributeError: 'module' object has no attribute 'dropbox_account_list'

**Comment by TomBaxter** [comment]
Not sure where things went wrong, but I reinstalled my dev environment from scratch and am no longer getting an error.

**Comment by sloria** [comment]
This will happen due to cached Python bytecode in pyc files. You can fix this in the future with `invoke clean`.
