### ISSUE TITLE
get a coverage report for JavaScript

### ISSUE THREAD

**Issue by whit537** [CenterForOpenScience/osf.io#4908]
Reticketing from #4799 to avoid noise over there.

**Comment by whit537** [comment]
I'm seeing a couple failures on #4799, I'm not going to worry about that here. I'm just looking at coverage.

```
    FormattableDate
      ✓ should have local and utc time
      ✗ should parse date strings
        AssertionError: expected 5 to equal 0
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:2911:0 <- webpack:
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:4723:0 <- webpack:
            at assertDateEqual (/Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:9
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:94949:0 <- webpack

      ✓ should parse datetime strings
      ✗ should allow datetimes with UTC offsets
        AssertionError: expected 15 to equal 10
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:2911:0 <- webpack:
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:4723:0 <- webpack:
            at assertDateEqual (/Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:9
            at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:94961:0 <- webpack
```

**Comment by whit537** [comment]
I'm starting with https://github.com/karma-runner/karma-coverage#examples.

**Comment by whit537** [comment]
I ran `npm install karma-coverage --save-dev`.

**Comment by whit537** [comment]
With this diff:

```diff
diff --git a/karma.conf.js b/karma.conf.js
index 48635ba..998f272 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -4,6 +4,7 @@ var assign = require('object-assign');
 module.exports = function (config) {
     config.set(assign(commonConfig, {
         browsers: ['PhantomJS'],
-        reporters: ['spec'],
+        reporters: ['spec', 'coverage'],
+        coverageReporter: {type: 'text'}
     }));
 };
diff --git a/package.json b/package.json
index 6c392a5..25e0707 100644
--- a/package.json
+++ b/package.json
@@ -65,6 +65,7 @@
     "jshint": "2.8.0",
     "karma": "^0.12.31",
     "karma-chrome-launcher": "^0.1.7",
+    "karma-coverage": "^0.5.3",
     "karma-firefox-launcher": "^0.1.4",
     "karma-mocha": "^0.1.10",
     "karma-phantomjs-launcher": "^0.1.4",
```

I get this output from `inv karma --single`

```
[...]
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 269 of 271 (2 FAILED) (skipped 2) (5.03 secs / 3.894 secs)

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|

[osf.io]$
```

**Comment by whit537** [comment]
Looks like the indirect [way](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.common.conf.js#L45-L47) in which we load tests stymies `karma-coverage`.

**Comment by whit537** [comment]
Here's a diff trying to specify a single test file:

```diff
diff --git a/karma.conf.js b/karma.conf.js
index 48635ba..94192a4 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -4,6 +4,8 @@ var assign = require('object-assign');
 module.exports = function (config) {
     config.set(assign(commonConfig, {
         browsers: ['PhantomJS'],
-        reporters: ['spec'],
+        reporters: ['spec', 'coverage'],
+        coverageReporter: {type: 'text'},
+        files: ['website/static/js/tests/contributors.test.js']
     }));
 };
```

Looks like that shortcuts a necessary compilation step (Coffeescript? ES6?):

```
[osf.io]$ inv karma --single
/Users/whit537/workbench/cos/osf.io/node_modules/karma/bin/karma start --single-run
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket jfMphcFPaT81t6jBvz_U with id 51317292
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  SyntaxError: Parse error
  at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/contributors.test.js:23

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.046 secs / 0 secs)

[osf.io]$
```

**Comment by whit537** [comment]
https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/website/static/js/tests/contributors.test.js#L23

**Comment by whit537** [comment]
Alright, so where does the Coffeescript/ES6 compilation happen in the normal `inv karma` flow?

**Comment by whit537** [comment]
What the heck is [this magic](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/website/static/js/tests/tests.webpack.js#L10)?

```javascript
context.keys().forEach(context);
```

**Comment by whit537** [comment]
What is a `require.context()`?

**Comment by whit537** [comment]
https://webpack.github.io/docs/context.html

**Comment by whit537** [comment]
https://webpack.github.io/docs/context.html#require-context

**Comment by whit537** [comment]
Smells like we're implementing https://github.com/webpack/karma-webpack#alternative-usage.

**Comment by whit537** [comment]
`google karma webpack coverage --lucky`

https://github.com/webpack/karma-webpack/issues/21

**Comment by whit537** [comment]
https://github.com/deepsweet/istanbul-instrumenter-loader

**Comment by whit537** [comment]
Here's a screenshot of what I'm trying to achieve, from https://github.com/douglasduteil/isparta#with-karma:

![screenshot](https://cloud.githubusercontent.com/assets/134455/12400195/a1acc28a-bdec-11e5-846f-a21331811f63.png)

**Comment by whit537** [comment]
So it *is* possible! :-)

Now, how to make it work?

What are the pieces?

**Comment by whit537** [comment]
1. webpack
1. karma
1. karma-coverage
1. istanbul
1. isparta
1. babel
1. istanbul-instrumenter-loader

**Comment by whit537** [comment]
> What the heck is [this magic](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/website/static/js/tests/tests.webpack.js#L10)?

Looks from a `console.log` that the keys of the context object are the filenames matched by the regex. And it looks from [source](https://github.com/webpack/webpack/blob/v1.7.2/lib/dependencies/RequireContextDependencyParserPlugin.js) that webpack is a complex piece of software.

**Comment by whit537** [comment]
Yikes, okay! Looks from a `console.log` that `request.context` returns a `webpackContext` object, and a repo search indicates that this object is [created dynamically](https://github.com/webpack/webpack/blob/v1.7.2/lib/ContextModule.js#L90-L104), per the [example](https://github.com/webpack/webpack/tree/v1.7.2/examples/require.context#jsoutputjs).

**Comment by whit537** [comment]
(I'm not sure how the `ContextDependency` code relates to `websiteContext`.)

**Comment by whit537** [comment]
[`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)

**Comment by whit537** [comment]
And calling the context object as a function [does](https://github.com/webpack/webpack/blob/v1.7.2/lib/ContextModule.js#L93):

```javascript
__webpack_require__(webpackContextResolve(req))
```

Where `webpackContextResolve` simply dereferences a module ID from the requirement name. Of course, `__webpack_require__` is also [dynamically written](https://github.com/webpack/webpack/blob/v1.7.2/lib/MainTemplate.js#L98-L121). :weary:

**Comment by whit537** [comment]
Thence down into Webpack's plugin system. :rabbit2:

Alright, so `__webpack_require__` requires each file passed to it, those enumerated in `context`. Bit of a goofy idiom, but there it is.

Okay!

**Comment by whit537** [comment]
Now we have `context` and `addonContext` objects in `tests.webpack.js`, and we've used those to load all of the test files. My understanding at this point (I could be wrong) is that the `context` and `addonContext` objects are disposable at this point. We don't them once we've used them to load the actual test scripts.

**Comment by whit537** [comment]
Presumably the [preprocessor](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.common.conf.js#L51) is where the ES6 compilation happens?

I see `babel` [mentioned](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/webpack.common.config.js#L182) in there ...

**Comment by whit537** [comment]
Though it looks like that's only for files with `.es6.` in the name.

**Comment by whit537** [comment]
Running without the preprocessor fails with:

```
[osf.io]$ inv karma --single
/Users/whit537/workbench/cos/osf.io/node_modules/karma/bin/karma start --single-run
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket PasiPGPlY37xY0XZg-6U with id 26838516
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:5

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.106 secs / 0 secs)

[osf.io]$
```

**Comment by whit537** [comment]
[object-assign](https://www.npmjs.com/package/object-assign)

**Comment by whit537** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172624973

I think this is how it goes?

```
karma
 karma-coverage
  isparta-loader
   isparta
    istanbul
     karma-webpack
      webpack
    babel
```

**Comment by whit537** [comment]
`webpack` is a preprocessor as far as `karma` is concerned.

> Be aware that preprocessors may be transforming the files and file types that are available at run time. For instance, if you are using the "coverage" preprocessor on your source files, if you then attempt to interactively debug your tests, you'll discover that your expected source code is completely changed from what you expected. Because of that, you'll want to engineer this so that your automated builds use the coverage entry in the "reporters" list, but your interactive debugging does not.

https://karma-runner.github.io/0.12/config/configuration-file.html

**Comment by whit537** [comment]
When I change the [`babel`](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.common.conf.js#L33) to `isparta`, I get this error:

```
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket VGCYaK-QqGbv7irN8TMx with id 34095188
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  SyntaxError: Parse error
  at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:1998:0 <- webpack:///website/static/js/tests/addons/addonNodeConfig.test.js:9:0

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.707 secs / 0 secs)

[osf.io]$
```

**Comment by whit537** [comment]
Is it supposed to be `isparta` or `isparta-loader`? The `isparta-loader` docs [say](https://github.com/deepsweet/isparta-loader/blob/000551e04924d45de38152fca93784e8122b5817/README.md) the latter, but they also show `babel` for another part of the config and we're using `babel-loader`. Maybe `karma` (or `webpack`?) accepts both?

**Comment by whit537** [comment]
`isparta` fails with the same error as `isparta-loader`, which leads me to believe that `karma` (or is it `webpack`?) accepts both. :fried_shrimp:

**Comment by whit537** [comment]
Golly ... now what's https://github.com/deepsweet/babel-istanbul-loader?

**Comment by whit537** [comment]
:disappointed:

**Comment by whit537** [comment]
https://github.com/ambitioninc/babel-istanbul

**Comment by whit537** [comment]
There's an "instrumentation" layer ... to `karma`? `webpack`?

**Comment by whit537** [comment]
![screen shot 2016-01-18 at 6 02 46 pm](https://cloud.githubusercontent.com/assets/134455/12404903/b38844ae-be0d-11e5-9839-122d4e1652c1.png)

**Comment by whit537** [comment]
:sob: 

![screen shot 2016-01-18 at 6 03 52 pm](https://cloud.githubusercontent.com/assets/134455/12404935/eb0840fa-be0d-11e5-9a7b-d1da3a588f8b.png)
![screen shot 2016-01-18 at 6 04 03 pm](https://cloud.githubusercontent.com/assets/134455/12404936/eb094c2a-be0d-11e5-8a35-73e1284c1ed7.png)

**Comment by whit537** [comment]
So `isparta-webpack-karma-istanbul-babel-istanbul` invented instrumenting? :weary:

**Comment by whit537** [comment]
Sorry, forgot `-loader-coverage-cover-instrumenter`.

**Comment by whit537** [comment]
/me tries `npm install isparta-webpack-karma-istanbul-babel-istanbul-loader-coverage-cover-instrumenter`

**Comment by whit537** [comment]
:disappointed: 

![screen shot 2016-01-18 at 6 06 35 pm](https://cloud.githubusercontent.com/assets/134455/12404975/38d7f3c0-be0e-11e5-8c44-bc0688bb86e3.png)

**Comment by whit537** [comment]
Karma is the test runner. Let's start there.

**Comment by whit537** [comment]
Karma [loads config](https://karma-runner.github.io/0.12/config/configuration-file.html) from `./karma.conf.js`.

**Comment by whit537** [comment]
Our `karma.conf.js` [requires](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.conf.js#L1) `karma.common.conf.js`.

**Comment by whit537** [comment]
(That's Node's `require`, right? Not Webpack's?)

**Comment by whit537** [comment]
Looks like probably:

```
[osf.io]$ inv karma --single
/Users/whit537/workbench/cos/osf.io/node_modules/karma/bin/karma start --single-run
{ [Function: require]
  resolve: [Function],
  main: 
   Module {
     id: '.',
     exports: {},
     parent: null,
     filename: '/Users/whit537/workbench/cos/osf.io/node_modules/karma/bin/karma',
     loaded: false,
     children: [ [Object] ],
     paths: 
[...]
```

```diff
diff --git a/karma.conf.js b/karma.conf.js
index 48635ba..059b749 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -1,3 +1,5 @@
+console.log(require);
+process.exit();
 var commonConfig = require('./karma.common.conf.js');
 var assign = require('object-assign');

```

**Comment by whit537** [comment]
Alright, so we require `commonConfig` and then override a couple attributes using ponyfilled `assign` before passing in to [`config.set`](https://karma-runner.github.io/0.12/config/configuration-file.html).

**Comment by whit537** [comment]
Here are the config keys set in [`karma.common.conf.js`](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.common.conf.js#L38-L64):

 - frameworks
 - files
 - preprocessors
 - webpack
 - webpackMiddleware
 - webpackServer
 - browserDisconnectTimeout
 - browserDisconnectTolerance
 - browserNoActivityTimeout

**Comment by whit537** [comment]
Here's where they come from:

##### [karma](https://karma-runner.github.io/0.12/config/configuration-file.html)

 - frameworks
 - files
 - preprocessors
 - browserDisconnectTimeout
 - browserDisconnectTolerance
 - browserNoActivityTimeout

##### [karma-webpack](https://github.com/webpack/karma-webpack/blob/v1.5.1/index.js#L9-L11)

 - webpack
 - webpackMiddleware
 - webpackServer

**Comment by whit537** [comment]
Re: `files`: https://karma-runner.github.io/0.12/config/files.html

**Comment by whit537** [comment]
> The `files` array determines which files are included in the browser and which files are watched and served by Karma.

**Comment by whit537** [comment]
We mimic loading jQuery, and then load `test.webpack.js` per the `karma-webpack` "[alternate usage](https://github.com/webpack/karma-webpack/tree/v1.5.1#alternative-usage)".

**Comment by whit537** [comment]
In other words, we specify a single file to load, and we specify the preprocessor supplied by `karma-webpack` to preprocess it.

**Comment by whit537** [comment]
Re: `preprocessors`: https://karma-runner.github.io/0.12/config/preprocessors.html.

**Comment by whit537** [comment]
`karma-coverage` supplies both `preprocessor` and a `reporter`.

**Comment by whit537** [comment]
[ [previous](https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172663823) ]

So far, then:

```
karma
 karma-webpack
  webpack
 karma-coverage
```

**Comment by whit537** [comment]
Alright ... so ... since `karma-webpack` and `karma-coverage` both operate via `preprocessors`, that's why we need an additional shim for them to cooperate?

**Comment by whit537** [comment]
[`istanbul-instrumenter-loader`](https://github.com/deepsweet/istanbul-instrumenter-loader) is a shim for `webpack` to provide the instrumentation that the `karma-coverage` `reporter` needs. It replaces the `karma-coverage` *`preprocessor`*, ya?

**Comment by whit537** [comment]
"Loaders" are a Webpack [concept](https://webpack.github.io/docs/using-loaders.html).

**Comment by whit537** [comment]
[ [prev](https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172684239) ]

```
karma
 karma-webpack
  webpack                        via a karma preprocessor
   istanbul-instrumenter-loader  via a webpack loader
    istanbul
 karma-coverage                  via a karma reporter
```

**Comment by whit537** [comment]
My hypothesis is that [`isparta-loader`](https://github.com/deepsweet/isparta-loader/) and [`babel-istanbul-loader`](https://github.com/deepsweet/babel-istanbul-loader/) are parallel. The latter is newer. All four commits on it are from 11 days ago, and the latest commit on the former is a README update pointing to the latter, also from 11 days ago.

**Comment by whit537** [comment]
`isparta-loader` depends on [`istanbul`](https://github.com/douglasduteil/isparta).

`babel-istanbul-loader` depends on [`babel-istanbul`](https://github.com/ambitioninc/babel-istanbul).

**Comment by whit537** [comment]
Let's try the newer one ...

**Comment by whit537** [comment]
[ [previous](https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172688257 ) ]

```
karma
 karma-webpack
  webpack                        via a karma preprocessor
   babel-istanbul-loader         via a webpack loader
    babel-istanbul
     istanbul
 karma-coverage                  via a karma reporter
```

**Comment by whit537** [comment]
Go science! :bulb:

**Comment by whit537** [comment]
Alright, now let's look at `loaders` and `preLoaders` in the `webpack` config we're passing in to `karma`.

**Comment by whit537** [comment]
> babel-istanbul is drop-in replacement for [istanbul](https://github.com/gotwarlost/istanbul), as it is a copy of istanbul with babel compilation inserted into the instrumentation layer.

https://github.com/ambitioninc/babel-istanbul/tree/c99056412584d6249996f3ac448cdb690d60a2d3#features

Hmm ... what are the implications of that for our plumbing?

**Comment by whit537** [comment]
[So arbitrary](https://webpack.github.io/docs/loaders.html#loader-order).

**Comment by whit537** [comment]
Alright, so [this example](https://github.com/deepsweet/babel-istanbul-loader/#karmaconfjs) still shows two separate [pre]loader configs, one for source files and one for tests scripts.

**Comment by whit537** [comment]
We only have [one](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/karma.common.conf.js#L33).

**Comment by whit537** [comment]
It's for test files.

**Comment by whit537** [comment]
Ah, but we're requiring `webpack.common.config.js`.

**Comment by whit537** [comment]
And using that to backfill the `webpackTestConfig`.

**Comment by whit537** [comment]
There's [bunch of loaders](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/webpack.common.config.js#L181-L194) in `webpackCommon`, but none are for plain `*.js` files (there are some for `*.es6.js`. Maybe the addon [config](https://github.com/CenterForOpenScience/osf.io/blob/86ddfa977ec25217002c8401a49042f1e37c0b17/webpack.common.config.js#L87-L101) is implicated in https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172675268?

**Comment by whit537** [comment]
So do we get the same parse error inside addons with `babel-istanbul-loader` as with `isparta-loader`?

**Comment by whit537** [comment]
No! But we get 14 test failures instead of 2 ...

```
  profile
    ViewModels
      NameViewModel
        ✗ "before each" hook for "calls $.ajax as POST request, and isCors flags sends credentials by default"
        timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 140 of 271 (14 FAILED) (skipped 1) (9.337 secs / NaN secs)

[osf.io]$
```

**Comment by whit537** [comment]
Now I can't reproduce the 14 errors, but I do get:

```
WARNING in Cannot find module 'loader-utils'
 @ ./website/static/js/tests .*test\.js$
```

**Comment by whit537** [comment]
`ack loader-utils` turns up nothing. :flushed: 

```
[osf.io]$ ack loader-utils
lines ?-?/? (END) 
```

**Comment by whit537** [comment]
With an `npm i -D loader-utils` I am back to https://github.com/CenterForOpenScience/osf.io/issues/4908#issuecomment-172675268:

```
 @ ./~/knockout/build/output/knockout-latest.js 7:222-229
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket m6CI47MnSDNGMA2sbjZG with id 94584439
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  SyntaxError: Parse error
  at /Users/whit537/workbench/cos/osf.io/website/static/js/tests/tests.webpack.js:1998:0 <- webpack:///website/static/js/tests/addons/addonNodeConfig.test.js:9:0

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.709 secs / 0 secs)

[osf.io]$ 
```

**Comment by whit537** [comment]
In other words, `babel-istanbul-loader` exhibits the same behavior as `isparta-loader`.

**Comment by whit537** [comment]
Alright, outta steam on this one. :weary:

I'll pick up ... probably on Friday, if it still looks worth it at that point.

Cheers! :-)
