### ISSUE TITLE
installation on Redhat fails

### ISSUE THREAD

**Issue by chrisfjell** [CenterForOpenScience/osf.io#5350]
I was following a modified version of the installation on Red Hat Enterprise Linux Server release 7.2 (Maipo). I seem to have installed all the non-python dependencies with yum package manager (will document separately).

I had the usual virtualenvwrapper in use etc as per instructions. The invoke tasks were failing because Red Hat wasn't recognized (only Ubuntu Linux appears coded-for) -- I ran pip or whatever to get those installed

All seemed good (or fixed) until running tests:

**invoke test_osf**

Many many tests report "ok" until:

test_a_public_component_from_home_page (tests.webtest_tests.TestSearching) ... Traceback (most recent call last):
  File "/home/cfjell/.workon_envs/osf/bin/invoke", line 9, in <module>
    load_entry_point('invoke==0.12.2', 'console_scripts', 'invoke')()
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/program.py", line 270, in run
    self.execute()
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/program.py", line 379, in execute
    executor.execute(_self.tasks)
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/executor.py", line 114, in execute
    result = call.task(_args, *_call.kwargs)
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/tasks.py", line 113, in **call**
    result = self.body(_args, *_kwargs)
  File "/home/cfjell/OSF_env/osf.io/tasks/**init**.py", line 467, in test_osf
    test_module(module="tests/")
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/tasks.py", line 113, in **call**
    result = self.body(_args, *_kwargs)
  File "/home/cfjell/OSF_env/osf.io/tasks/**init**.py", line 461, in test_module
    run(bin_prefix(TEST_CMD) + args, pty=True)
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/**init**.py", line 27, in run
    return Context().run(command, *_kwargs)
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/home/cfjell/.workon_envs/osf/lib/python2.7/site-packages/invoke/runners.py", line 280, in run
    raise ThreadException(exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (UnicodeEncodeError):
...
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-7: ordinal not in range(128)

Before I look in depth at why the test is failing, I wanted to put up an issue, in case it's obvious to someone else.

My motivation: 
1) We have restrictions on moving data out of the province and wanted to use our own server (_might_ be possible to use COS' OSF with alternate data storage pointing to our server)
2) I've developed with Django in the past and I hoped to put custom apps somewhat meshed with OSF. I might drop this idea and use plain Django.

I had hoped to fully document the install process on Red Hat for our expected needs - if that is a reasonable thing to do. I can start a page and that as part of resolving this issue with full steps involved.

Cheers,
-Chris

**Comment by sloria** [comment]
Thank you for reporting this @chrisfjell . 

What version of invoke are you running?

```bash
invoke --version
```

Our documentation Linux is admittedly lacking at the moment; we'd certainly review and merge a PR updating the docs for RHEL.
