### ISSUE TITLE
WaterBulter problem

### ISSUE THREAD

**Issue by umardraz** [CenterForOpenScience/osf.io#6254]
Hi

Would you please help me about this error, we are facing on WaterBulter

Raven is not configured (logging is disabled). Please see the documentation for more information.
[2016-08-30 10:33:36,548][INFO][raven.contrib.tornado.AsyncSentryClient]: Raven is not configured (logging is disabled). Please see the documentation for more information.
[2016-08-30 10:34:11,981][ERROR][tornado.application]: Uncaught exception GET /data?path=%2F&provider=osfstorage&nid=7wrgv&_=1472578451945 (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:7777', method='GET', uri='/data?path=%2F&provider=osfstorage&nid=7wrgv&_=1472578451945', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Host': 'localhost:7777', 'Origin': 'http://localhost:5000', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': 'application/json, text/*', 'Cookie': 'osf=57c5bc03e1382318501bd337.dDn9bbzaaDZf7xkC3TpyWr1v7ZE', 'User-Agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0', 'Referer': 'http://localhost:5000/7wrgv/'})
Traceback (most recent call last):
  File "/home/steve/git/waterbutler/lib/python3.5/site-packages/tornado/web.py", line 1424, in _execute
    result = yield result
  File "/home/steve/git/waterbutler/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/steve/git/waterbutler/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/steve/git/waterbutler/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "<string>", line 6, in _wrap_awaitable
TypeError: throw() takes 2 positional arguments but 4 were given

**Comment by felliott** [comment]
Hey @umardraz,

There's a bug in core python that makes WaterButler (and MFR) not work when Tornado server debugging is turned on.  See [this page](https://github.com/CenterForOpenScience/waterbutler#testing-configuration-optional) for instructions on how to disable it.

Also, if you run into issues with WaterButler or MFR please report it in their issue trackers.  I'm much more likely to see it if you post there.

Cheers,
@felliott
