### ISSUE TITLE
Failed building requirements container

### ISSUE THREAD

**Issue by fugokidi** [CenterForOpenScience/osf.io#8905]
While following `README-docker-compose.md`, specifically,
`docker-compose up requirements`, I got the error:
```
requirements_1      | Installing requirements for dataverse
requirements_1      | /usr/local/bin/pip install --exists-action w --upgrade -r /code/addons/dataverse/requirements.txt  -c /code/requirements/constraints.txt
requirements_1      | Obtaining dataverse from git+https://github.com/CenterForOpenScience/dataverse-client-python.git@48dd0edfa396a51d28e08518d72e4fa825427073#egg=dataverse (from -r /code/addons/dataverse/requirements.txt (line 4))
requirements_1      |   Cloning https://github.com/CenterForOpenScience/dataverse-client-python.git (to revision 48dd0edfa396a51d28e08518d72e4fa825427073) to ./src/dataverse
requirements_1      | Traceback (most recent call last):
requirements_1      |   File "/usr/local/bin/invoke", line 11, in <module>
requirements_1      |     sys.exit(program.run())
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 293, in run
requirements_1      |     self.execute()
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 408, in execute
requirements_1      |     executor.execute(*self.tasks)
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/executor.py", line 114, in execute
requirements_1      |     result = call.task(*args, **call.kwargs)
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 114, in __call__
requirements_1      |     result = self.body(*args, **kwargs)
requirements_1      |   File "/code/tasks/__init__.py", line 247, in requirements
requirements_1      |     addon_requirements(ctx)
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 114, in __call__
requirements_1      |     result = self.body(*args, **kwargs)
requirements_1      |   File "/code/tasks/__init__.py", line 534, in addon_requirements
requirements_1      |     echo=True
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/context.py", line 70, in run
requirements_1      |     return runner_class(context=self).run(command, **kwargs)
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 259, in run
requirements_1      |     return self._run_body(command, **kwargs)
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 361, in _run_body
requirements_1      |     raise ThreadException(thread_exceptions)
requirements_1      | invoke.exceptions.ThreadException:
requirements_1      | Saw 1 exceptions within threads (IOError):
requirements_1      |
requirements_1      |
requirements_1      | Thread args: {'kwargs': {'echo': None,
requirements_1      |             'input_': <open file '<stdin>', mode 'r' at 0x7f96c568d0c0>,
requirements_1      |             'output': <open file '<stdout>', mode 'w' at 0x7f96c568d150>},
requirements_1      |  'target': <bound method Local.handle_stdin of <invoke.runners.Local object at 0x7f96be9d0890>>}
requirements_1      |
requirements_1      | Traceback (most recent call last):
requirements_1      |
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/util.py", line 142, in run
requirements_1      |     super(ExceptionHandlingThread, self).run()
requirements_1      |
requirements_1      |   File "/usr/local/lib/python2.7/threading.py", line 754, in run
requirements_1      |     self.__target(*self.__args, **self.__kwargs)
requirements_1      |
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 624, in handle_stdin
requirements_1      |     data = self.read_our_stdin(input_)
requirements_1      |
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 586, in read_our_stdin
requirements_1      |     bytes_ = input_.read(bytes_to_read(input_))
requirements_1      |
requirements_1      |   File "/usr/local/lib/python2.7/site-packages/invoke/platform.py", line 162, in bytes_to_read
requirements_1      |     return struct.unpack('h', fcntl.ioctl(input_, termios.FIONREAD, "  "))[0]
requirements_1      |
requirements_1      | IOError: [Errno 25] Inappropriate ioctl for device
requirements_1      |
requirements_1      |
osfio_requirements_1 exited with code 1
```
Can anyone shed some lights on this please?

**Comment by towicode** [comment]
Running into the same issue. 

https://github.com/CenterForOpenScience/dataverse-client-python.git@48dd0edfa396a51d28e08518d72e4fa825427073#egg=dataverse  Doesn't exist.

and even when I replace it with 

https://github.com/IQSS/dataverse-client-python.git#egg=dataverse

i get the same error

`requirements_1      | IOError: [Errno 25] Inappropriate ioctl for device`
