### ISSUE TITLE
Wiki: Fix wiki crash, when wiki link contains UTF chars only.

### ISSUE THREAD

**Issue by ebijun** [CenterForOpenScience/osf.io#9254]
In creating wiki link,always crushing, if wiki link contains UTF chars only.
with
 ERROR: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Fix:

add u to return value.

File "addons/wiki/models.py", line 94, in build_wiki_url
    return '/{pid}/wiki/{wname}/'.format(pid=node._id, wname=label)
to:
File "addons/wiki/models.py", line 94, in build_wiki_url
    return u'/{pid}/wiki/{wname}/'.format(pid=node._id, wname=label)

Traces:
[framework.routing]  ERROR: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Traceback (most recent call last):
  File "./framework/routing/__init__.py", line 117, in wrapped
    data = fn(*args, **kwargs)
  File "./osf/utils/tokens/__init__.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "./website/project/decorators.py", line 110, in wrapped
    return func(*args, **kwargs)
  File "./website/project/decorators.py", line 301, in wrapped
    return response or func(*args, **kwargs)
  File "./website/ember_osf_web/decorators.py", line 21, in wrapped
    return func(*args, **kwargs)
  File "./website/project/views/node.py", line 535, in view_project
    addons_widget_data['wiki'] = serialize_wiki_widget(node)
  File "./addons/wiki/utils.py", line 242, in serialize_wiki_widget
    if wiki_version and wiki_version.html(node):
  File "./addons/wiki/models.py", line 133, in html
    html_output = build_html_output(self.content, node=node)
  File "./addons/wiki/models.py", line 79, in build_html_output
    [('css_class', 'highlight')]
  File "/usr/local/lib/python2.7/site-packages/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/usr/local/lib/python2.7/site-packages/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "/usr/local/lib/python2.7/site-packages/markdown/treeprocessors.py", line 295, in run
    self.__handleInline(text), child
  File "/usr/local/lib/python2.7/site-packages/markdown/treeprocessors.py", line 106, in __handleInline
    data, patternIndex, startIndex)
  File "/usr/local/lib/python2.7/site-packages/markdown/treeprocessors.py", line 239, in __applyPattern
    node = pattern.handleMatch(match)
  File "/usr/local/lib/python2.7/site-packages/markdown/extensions/wikilinks.py", line 63, in handleMatch
    url = self.config['build_url'](label, base_url, end_url)
  File "./addons/wiki/models.py", line 94, in build_wiki_url
    return '/{pid}/wiki/{wname}/'.format(pid=node._id, wname=label)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
[pid: 22|app: ?|req: ?/?] 136.187.176.154 (-) {56 vars in 1271 bytes} [Wed Dec  4 01:56:43 2019] GET /64gzk/ => generated 13548 bytes in 498 msecs (HTTP/1.1 500) 4 headers in 292 bytes (3 switches on core 485) "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15"

**Comment by Johnetordoff** [comment]
Recent updates to osf.io have fixed this problem, namely our conversion to Python 3. If you update your instance this problem should go away.

**Comment by ebijun** [comment]
Thanx for fixing!
